"""Initial migration

Revision ID: 530d51994c6d
Revises: 
Create Date: 2024-02-16 18:49:24.061769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530d51994c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_model')
    # ### end Alembic commands ###
