"""0003 index

Revision ID: 5a659520e7cc
Revises: fd5df838f2ec
Create Date: 2024-02-18 20:00:26.649506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a659520e7cc'
down_revision = 'fd5df838f2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index('_full_name')
        batch_op.create_unique_constraint('_full_name', ['name', 'surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('_full_name', type_='unique')
        batch_op.create_index('_full_name', ['name', 'surname'], unique=1)

    # ### end Alembic commands ###
