"""0004 add raiting column

Revision ID: 65ed4f29d573
Revises: 5a659520e7cc
Create Date: 2024-02-18 20:29:48.231438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ed4f29d573'
down_revision = '5a659520e7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raiting', sa.Integer(), server_default='3', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('raiting')

    # ### end Alembic commands ###
