"""0002 add surname

Revision ID: fd5df838f2ec
Revises: 7e2969c96b22
Create Date: 2024-02-18 19:37:03.687372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5df838f2ec'
down_revision = '7e2969c96b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), server_default='nosurname', nullable=False))
        batch_op.create_unique_constraint('_full_name', ['name', 'surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('_full_name', type_='unique')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
